// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package sqlc

import (
	"context"
)

const getMonthlyUsage = `-- name: GetMonthlyUsage :one
SELECT
    coalesce(sum(input_tokens), 0)::int as total_input_tokens,
    coalesce(sum(output_tokens), 0)::int as total_output_tokens,
    coalesce(count(*), 0)::int as total_requests
FROM ai_usage_log
WHERE user_id = $1
    AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)
    AND created_at < date_trunc('month', CURRENT_TIMESTAMP) + interval '1 month'
`

type GetMonthlyUsageRow struct {
	TotalInputTokens  int32 `json:"total_input_tokens"`
	TotalOutputTokens int32 `json:"total_output_tokens"`
	TotalRequests     int32 `json:"total_requests"`
}

func (q *Queries) GetMonthlyUsage(ctx context.Context, userID *int64) (GetMonthlyUsageRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyUsage, userID)
	var i GetMonthlyUsageRow
	err := row.Scan(&i.TotalInputTokens, &i.TotalOutputTokens, &i.TotalRequests)
	return i, err
}

const logAIUsage = `-- name: LogAIUsage :one
INSERT INTO ai_usage_log (user_id, conversation_id, input_tokens, output_tokens, model)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, conversation_id, input_tokens, output_tokens, model, created_at
`

type LogAIUsageParams struct {
	UserID         *int64 `json:"user_id"`
	ConversationID *int64 `json:"conversation_id"`
	InputTokens    int32  `json:"input_tokens"`
	OutputTokens   int32  `json:"output_tokens"`
	Model          string `json:"model"`
}

func (q *Queries) LogAIUsage(ctx context.Context, arg LogAIUsageParams) (AiUsageLog, error) {
	row := q.db.QueryRow(ctx, logAIUsage,
		arg.UserID,
		arg.ConversationID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Model,
	)
	var i AiUsageLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
