// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"
	"time"
)

const getConnectionDensity = `-- name: GetConnectionDensity :one
SELECT
    count(DISTINCT n.id)::int as active_notes,
    count(DISTINCT c.id)::int as total_connections,
    count(DISTINCT CASE WHEN c.id IS NULL THEN n.id END)::int as orphan_count
FROM notes n
LEFT JOIN (
    SELECT id, source_id as note_id FROM connections
    UNION ALL
    SELECT id, target_id as note_id FROM connections
) c ON c.note_id = n.id
WHERE n.user_id = $1
    AND n.status IN ('active', 'linked')
`

type GetConnectionDensityRow struct {
	ActiveNotes      int32 `json:"active_notes"`
	TotalConnections int32 `json:"total_connections"`
	OrphanCount      int32 `json:"orphan_count"`
}

func (q *Queries) GetConnectionDensity(ctx context.Context, userID int64) (GetConnectionDensityRow, error) {
	row := q.db.QueryRow(ctx, getConnectionDensity, userID)
	var i GetConnectionDensityRow
	err := row.Scan(&i.ActiveNotes, &i.TotalConnections, &i.OrphanCount)
	return i, err
}

const getConversationConversionRate = `-- name: GetConversationConversionRate :one
SELECT
    count(DISTINCT conv.id)::int as total_conversations,
    count(DISTINCT n.source_chat_id)::int as conversations_with_notes
FROM conversations conv
LEFT JOIN notes n ON n.source_chat_id = conv.id
WHERE conv.user_id = $1
`

type GetConversationConversionRateRow struct {
	TotalConversations     int32 `json:"total_conversations"`
	ConversationsWithNotes int32 `json:"conversations_with_notes"`
}

func (q *Queries) GetConversationConversionRate(ctx context.Context, userID int64) (GetConversationConversionRateRow, error) {
	row := q.db.QueryRow(ctx, getConversationConversionRate, userID)
	var i GetConversationConversionRateRow
	err := row.Scan(&i.TotalConversations, &i.ConversationsWithNotes)
	return i, err
}

const getFleetingNotesWithAge = `-- name: GetFleetingNotesWithAge :many
SELECT n.id, n.title, n.summary, n.core_idea, n.body, n.laymans_terms,
    n.analogy, n.components, n.why_it_matters, n.examples, n.templates,
    n.additional, n.note_type, n.created_at, n.updated_at
FROM notes n
WHERE n.user_id = $1 AND n.status = 'fleeting'
ORDER BY n.created_at ASC
`

type GetFleetingNotesWithAgeRow struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Summary      string    `json:"summary"`
	CoreIdea     string    `json:"core_idea"`
	Body         string    `json:"body"`
	LaymansTerms string    `json:"laymans_terms"`
	Analogy      string    `json:"analogy"`
	Components   string    `json:"components"`
	WhyItMatters string    `json:"why_it_matters"`
	Examples     string    `json:"examples"`
	Templates    string    `json:"templates"`
	Additional   string    `json:"additional"`
	NoteType     NoteType  `json:"note_type"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetFleetingNotesWithAge(ctx context.Context, userID int64) ([]GetFleetingNotesWithAgeRow, error) {
	rows, err := q.db.Query(ctx, getFleetingNotesWithAge, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFleetingNotesWithAgeRow{}
	for rows.Next() {
		var i GetFleetingNotesWithAgeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.CoreIdea,
			&i.Body,
			&i.LaymansTerms,
			&i.Analogy,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlossaryCount = `-- name: GetGlossaryCount :one
SELECT count(*)::int as count FROM glossary_terms WHERE user_id = $1
`

func (q *Queries) GetGlossaryCount(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getGlossaryCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLifecycleMetrics = `-- name: GetLifecycleMetrics :many
SELECT
    to_status,
    count(*) as transition_count,
    avg(EXTRACT(EPOCH FROM (ne.created_at - prev.created_at)))::bigint as avg_dwell_seconds
FROM note_events ne
JOIN LATERAL (
    SELECT created_at FROM note_events prev
    WHERE prev.note_id = ne.note_id
        AND prev.created_at < ne.created_at
    ORDER BY prev.created_at DESC
    LIMIT 1
) prev ON true
WHERE ne.user_id = $1
    AND ne.from_status = 'fleeting'
    AND ne.to_status IN ('active', 'sleeping', 'archived')
    AND ne.created_at >= $2
GROUP BY ne.to_status
`

type GetLifecycleMetricsParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetLifecycleMetricsRow struct {
	ToStatus        NoteStatus `json:"to_status"`
	TransitionCount int64      `json:"transition_count"`
	AvgDwellSeconds int64      `json:"avg_dwell_seconds"`
}

func (q *Queries) GetLifecycleMetrics(ctx context.Context, arg GetLifecycleMetricsParams) ([]GetLifecycleMetricsRow, error) {
	rows, err := q.db.Query(ctx, getLifecycleMetrics, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLifecycleMetricsRow{}
	for rows.Next() {
		var i GetLifecycleMetricsRow
		if err := rows.Scan(&i.ToStatus, &i.TransitionCount, &i.AvgDwellSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLifecycleTrend = `-- name: GetLifecycleTrend :many
SELECT
    date_trunc('week', ne.created_at)::timestamptz as week,
    ne.to_status,
    count(*)::bigint as count
FROM note_events ne
WHERE ne.user_id = $1
    AND ne.from_status = 'fleeting'
    AND ne.to_status IN ('active', 'sleeping', 'archived')
    AND ne.created_at >= $2
GROUP BY week, ne.to_status
ORDER BY week ASC
`

type GetLifecycleTrendParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetLifecycleTrendRow struct {
	Week     time.Time  `json:"week"`
	ToStatus NoteStatus `json:"to_status"`
	Count    int64      `json:"count"`
}

func (q *Queries) GetLifecycleTrend(ctx context.Context, arg GetLifecycleTrendParams) ([]GetLifecycleTrendRow, error) {
	rows, err := q.db.Query(ctx, getLifecycleTrend, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLifecycleTrendRow{}
	for rows.Next() {
		var i GetLifecycleTrendRow
		if err := rows.Scan(&i.Week, &i.ToStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteTypeDistribution = `-- name: GetNoteTypeDistribution :many
SELECT note_type, count(*) as count
FROM notes
WHERE user_id = $1 AND status IN ('active', 'linked')
GROUP BY note_type
`

type GetNoteTypeDistributionRow struct {
	NoteType NoteType `json:"note_type"`
	Count    int64    `json:"count"`
}

func (q *Queries) GetNoteTypeDistribution(ctx context.Context, userID int64) ([]GetNoteTypeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getNoteTypeDistribution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNoteTypeDistributionRow{}
	for rows.Next() {
		var i GetNoteTypeDistributionRow
		if err := rows.Scan(&i.NoteType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSleepingNoteStats = `-- name: GetSleepingNoteStats :one
SELECT
    count(*)::int as count,
    coalesce(avg(EXTRACT(EPOCH FROM (NOW() - created_at)))::bigint, 0) as avg_age_seconds
FROM notes
WHERE user_id = $1 AND status = 'sleeping'
`

type GetSleepingNoteStatsRow struct {
	Count         int32       `json:"count"`
	AvgAgeSeconds interface{} `json:"avg_age_seconds"`
}

func (q *Queries) GetSleepingNoteStats(ctx context.Context, userID int64) (GetSleepingNoteStatsRow, error) {
	row := q.db.QueryRow(ctx, getSleepingNoteStats, userID)
	var i GetSleepingNoteStatsRow
	err := row.Scan(&i.Count, &i.AvgAgeSeconds)
	return i, err
}

const getStaleNotes = `-- name: GetStaleNotes :many
SELECT id, title, note_type, updated_at
FROM notes
WHERE user_id = $1
    AND status IN ('active', 'linked')
    AND updated_at < NOW() - make_interval(days => $2::int)
ORDER BY updated_at ASC
LIMIT 10
`

type GetStaleNotesParams struct {
	UserID  int64 `json:"user_id"`
	Column2 int32 `json:"column_2"`
}

type GetStaleNotesRow struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	NoteType  NoteType  `json:"note_type"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetStaleNotes(ctx context.Context, arg GetStaleNotesParams) ([]GetStaleNotesRow, error) {
	rows, err := q.db.Query(ctx, getStaleNotes, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleNotesRow{}
	for rows.Next() {
		var i GetStaleNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.NoteType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
