// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package sqlc

import (
	"context"
	"time"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (source_id, target_id, label)
SELECT $1::bigint, $2::bigint, $3::text
WHERE EXISTS (SELECT 1 FROM notes src WHERE src.id = $1 AND src.user_id = $4)
  AND EXISTS (SELECT 1 FROM notes tgt WHERE tgt.id = $2 AND tgt.user_id = $4)
RETURNING id, source_id, target_id, label, created_at
`

type CreateConnectionParams struct {
	SourceID int64  `json:"source_id"`
	TargetID int64  `json:"target_id"`
	Label    string `json:"label"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.SourceID,
		arg.TargetID,
		arg.Label,
		arg.UserID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections c
USING notes src, notes tgt
WHERE c.id = $1
  AND src.id = c.source_id AND src.user_id = $2
  AND tgt.id = c.target_id AND tgt.user_id = $2
`

type DeleteConnectionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Checks both endpoints, matching ListConnectionsForNote. Source-only would be
// enough for rows created after CreateConnection was scoped, but not for any
// cross-owner rows left behind from before that fix.
func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteConnection, arg.ID, arg.UserID)
	return err
}

const getGraphData = `-- name: GetGraphData :many
SELECT c.source_id, c.target_id, c.label,
    n1.title as source_title, n1.note_type as source_type,
    n2.title as target_title, n2.note_type as target_type
FROM connections c
JOIN notes n1 ON n1.id = c.source_id
JOIN notes n2 ON n2.id = c.target_id
WHERE n1.user_id = $1 AND n2.user_id = $1
`

type GetGraphDataRow struct {
	SourceID    int64    `json:"source_id"`
	TargetID    int64    `json:"target_id"`
	Label       string   `json:"label"`
	SourceTitle string   `json:"source_title"`
	SourceType  NoteType `json:"source_type"`
	TargetTitle string   `json:"target_title"`
	TargetType  NoteType `json:"target_type"`
}

func (q *Queries) GetGraphData(ctx context.Context, userID int64) ([]GetGraphDataRow, error) {
	rows, err := q.db.Query(ctx, getGraphData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGraphDataRow{}
	for rows.Next() {
		var i GetGraphDataRow
		if err := rows.Scan(
			&i.SourceID,
			&i.TargetID,
			&i.Label,
			&i.SourceTitle,
			&i.SourceType,
			&i.TargetTitle,
			&i.TargetType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsForNote = `-- name: ListConnectionsForNote :many
SELECT c.id, c.source_id, c.target_id, c.label, c.created_at,
    CASE WHEN c.source_id = $1 THEN n2.title ELSE n1.title END as connected_title,
    CASE WHEN c.source_id = $1 THEN c.target_id ELSE c.source_id END as connected_id,
    CASE WHEN c.source_id = $1 THEN 'outgoing' ELSE 'incoming' END as direction
FROM connections c
JOIN notes n1 ON n1.id = c.source_id
JOIN notes n2 ON n2.id = c.target_id
WHERE (c.source_id = $1 OR c.target_id = $1)
  AND n1.user_id = $2
  AND n2.user_id = $2
`

type ListConnectionsForNoteParams struct {
	SourceID int64 `json:"source_id"`
	UserID   int64 `json:"user_id"`
}

type ListConnectionsForNoteRow struct {
	ID             int64       `json:"id"`
	SourceID       int64       `json:"source_id"`
	TargetID       int64       `json:"target_id"`
	Label          string      `json:"label"`
	CreatedAt      time.Time   `json:"created_at"`
	ConnectedTitle interface{} `json:"connected_title"`
	ConnectedID    interface{} `json:"connected_id"`
	Direction      string      `json:"direction"`
}

func (q *Queries) ListConnectionsForNote(ctx context.Context, arg ListConnectionsForNoteParams) ([]ListConnectionsForNoteRow, error) {
	rows, err := q.db.Query(ctx, listConnectionsForNote, arg.SourceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsForNoteRow{}
	for rows.Next() {
		var i ListConnectionsForNoteRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Label,
			&i.CreatedAt,
			&i.ConnectedTitle,
			&i.ConnectedID,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
