// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title, topic)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, topic, created_at, updated_at
`

type CreateConversationParams struct {
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
	Topic  string `json:"topic"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.UserID, arg.Title, arg.Topic)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, input_tokens, output_tokens, model)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, role, content, input_tokens, output_tokens, model, created_at
`

type CreateMessageParams struct {
	ConversationID int64  `json:"conversation_id"`
	Role           string `json:"role"`
	Content        string `json:"content"`
	InputTokens    int32  `json:"input_tokens"`
	OutputTokens   int32  `json:"output_tokens"`
	Model          string `json:"model"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Model,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, topic, created_at, updated_at FROM conversations WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, topic, created_at, updated_at FROM conversations
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, input_tokens, output_tokens, model, created_at FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE conversations SET title = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, topic, created_at, updated_at
`

type UpdateConversationTitleParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationTitle, arg.ID, arg.UserID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
