// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: glossary.sql

package sqlc

import (
	"context"
	"time"
)

const createGlossaryTerm = `-- name: CreateGlossaryTerm :one
INSERT INTO glossary_terms (user_id, term, definition, source_note_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, term, definition, source_note_id, created_at, updated_at
`

type CreateGlossaryTermParams struct {
	UserID       int64  `json:"user_id"`
	Term         string `json:"term"`
	Definition   string `json:"definition"`
	SourceNoteID *int64 `json:"source_note_id"`
}

func (q *Queries) CreateGlossaryTerm(ctx context.Context, arg CreateGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, createGlossaryTerm,
		arg.UserID,
		arg.Term,
		arg.Definition,
		arg.SourceNoteID,
	)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Term,
		&i.Definition,
		&i.SourceNoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGlossaryTerm = `-- name: DeleteGlossaryTerm :exec
DELETE FROM glossary_terms WHERE id = $1 AND user_id = $2
`

type DeleteGlossaryTermParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteGlossaryTerm(ctx context.Context, arg DeleteGlossaryTermParams) error {
	_, err := q.db.Exec(ctx, deleteGlossaryTerm, arg.ID, arg.UserID)
	return err
}

const listGlossaryTerms = `-- name: ListGlossaryTerms :many
SELECT g.id, g.user_id, g.term, g.definition, g.source_note_id, g.created_at, g.updated_at, n.title as source_note_title
FROM glossary_terms g
LEFT JOIN notes n ON n.id = g.source_note_id
WHERE g.user_id = $1
ORDER BY g.term
`

type ListGlossaryTermsRow struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	Term            string    `json:"term"`
	Definition      string    `json:"definition"`
	SourceNoteID    *int64    `json:"source_note_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	SourceNoteTitle *string   `json:"source_note_title"`
}

func (q *Queries) ListGlossaryTerms(ctx context.Context, userID int64) ([]ListGlossaryTermsRow, error) {
	rows, err := q.db.Query(ctx, listGlossaryTerms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlossaryTermsRow{}
	for rows.Next() {
		var i ListGlossaryTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Term,
			&i.Definition,
			&i.SourceNoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceNoteTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGlossaryTerm = `-- name: UpdateGlossaryTerm :one
UPDATE glossary_terms SET
    term = $3,
    definition = $4,
    source_note_id = $5,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, term, definition, source_note_id, created_at, updated_at
`

type UpdateGlossaryTermParams struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	Term         string `json:"term"`
	Definition   string `json:"definition"`
	SourceNoteID *int64 `json:"source_note_id"`
}

func (q *Queries) UpdateGlossaryTerm(ctx context.Context, arg UpdateGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, updateGlossaryTerm,
		arg.ID,
		arg.UserID,
		arg.Term,
		arg.Definition,
		arg.SourceNoteID,
	)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Term,
		&i.Definition,
		&i.SourceNoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
