// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type NoteStatus string

const (
	NoteStatusFleeting NoteStatus = "fleeting"
	NoteStatusSleeping NoteStatus = "sleeping"
	NoteStatusActive   NoteStatus = "active"
	NoteStatusLinked   NoteStatus = "linked"
	NoteStatusArchived NoteStatus = "archived"
)

func (e *NoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NoteStatus(s)
	case string:
		*e = NoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NoteStatus: %T", src)
	}
	return nil
}

type NullNoteStatus struct {
	NoteStatus NoteStatus `json:"note_status"`
	Valid      bool       `json:"valid"` // Valid is true if NoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NoteStatus), nil
}

type NoteTlp string

const (
	NoteTlpClear NoteTlp = "clear"
	NoteTlpGreen NoteTlp = "green"
	NoteTlpAmber NoteTlp = "amber"
	NoteTlpRed   NoteTlp = "red"
)

func (e *NoteTlp) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NoteTlp(s)
	case string:
		*e = NoteTlp(s)
	default:
		return fmt.Errorf("unsupported scan type for NoteTlp: %T", src)
	}
	return nil
}

type NullNoteTlp struct {
	NoteTlp NoteTlp `json:"note_tlp"`
	Valid   bool    `json:"valid"` // Valid is true if NoteTlp is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNoteTlp) Scan(value interface{}) error {
	if value == nil {
		ns.NoteTlp, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NoteTlp.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNoteTlp) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NoteTlp), nil
}

type NoteType string

const (
	NoteTypeConcept   NoteType = "concept"
	NoteTypeTheory    NoteType = "theory"
	NoteTypeInsight   NoteType = "insight"
	NoteTypeQuote     NoteType = "quote"
	NoteTypeReference NoteType = "reference"
	NoteTypeQuestion  NoteType = "question"
	NoteTypeStructure NoteType = "structure"
	NoteTypeGuide     NoteType = "guide"
)

func (e *NoteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NoteType(s)
	case string:
		*e = NoteType(s)
	default:
		return fmt.Errorf("unsupported scan type for NoteType: %T", src)
	}
	return nil
}

type NullNoteType struct {
	NoteType NoteType `json:"note_type"`
	Valid    bool     `json:"valid"` // Valid is true if NoteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNoteType) Scan(value interface{}) error {
	if value == nil {
		ns.NoteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NoteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNoteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NoteType), nil
}

type AiUsageLog struct {
	ID             int64     `json:"id"`
	UserID         *int64    `json:"user_id"`
	ConversationID *int64    `json:"conversation_id"`
	InputTokens    int32     `json:"input_tokens"`
	OutputTokens   int32     `json:"output_tokens"`
	Model          string    `json:"model"`
	CreatedAt      time.Time `json:"created_at"`
}

type Connection struct {
	ID        int64     `json:"id"`
	SourceID  int64     `json:"source_id"`
	TargetID  int64     `json:"target_id"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type Conversation struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Title     string    `json:"title"`
	Topic     string    `json:"topic"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type GlossaryTerm struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Term         string    `json:"term"`
	Definition   string    `json:"definition"`
	SourceNoteID *int64    `json:"source_note_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Message struct {
	ID             int64     `json:"id"`
	ConversationID int64     `json:"conversation_id"`
	Role           string    `json:"role"`
	Content        string    `json:"content"`
	InputTokens    int32     `json:"input_tokens"`
	OutputTokens   int32     `json:"output_tokens"`
	Model          string    `json:"model"`
	CreatedAt      time.Time `json:"created_at"`
}

type Note struct {
	ID           int64       `json:"id"`
	UserID       int64       `json:"user_id"`
	Title        string      `json:"title"`
	Summary      string      `json:"summary"`
	LaymansTerms string      `json:"laymans_terms"`
	Analogy      string      `json:"analogy"`
	CoreIdea     string      `json:"core_idea"`
	Body         string      `json:"body"`
	Components   string      `json:"components"`
	WhyItMatters string      `json:"why_it_matters"`
	Examples     string      `json:"examples"`
	Templates    string      `json:"templates"`
	Additional   string      `json:"additional"`
	NoteType     NoteType    `json:"note_type"`
	Status       NoteStatus  `json:"status"`
	Tlp          NoteTlp     `json:"tlp"`
	SourceChatID *int64      `json:"source_chat_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	SearchVector interface{} `json:"search_vector"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type User struct {
	ID          int64           `json:"id"`
	OidcSubject string          `json:"oidc_subject"`
	Email       string          `json:"email"`
	Name        string          `json:"name"`
	AvatarUrl   string          `json:"avatar_url"`
	Preferences json.RawMessage `json:"preferences"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
