// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlc

import (
	"context"
	"time"
)

const countNotesByStatus = `-- name: CountNotesByStatus :many
SELECT status, count(*) as count
FROM notes
WHERE user_id = $1
GROUP BY status
`

type CountNotesByStatusRow struct {
	Status NoteStatus `json:"status"`
	Count  int64      `json:"count"`
}

func (q *Queries) CountNotesByStatus(ctx context.Context, userID int64) ([]CountNotesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countNotesByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNotesByStatusRow{}
	for rows.Next() {
		var i CountNotesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    user_id, title, summary, laymans_terms, analogy, core_idea,
    body, components, why_it_matters, examples, templates, additional,
    note_type, status, tlp, source_chat_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector
`

type CreateNoteParams struct {
	UserID       int64      `json:"user_id"`
	Title        string     `json:"title"`
	Summary      string     `json:"summary"`
	LaymansTerms string     `json:"laymans_terms"`
	Analogy      string     `json:"analogy"`
	CoreIdea     string     `json:"core_idea"`
	Body         string     `json:"body"`
	Components   string     `json:"components"`
	WhyItMatters string     `json:"why_it_matters"`
	Examples     string     `json:"examples"`
	Templates    string     `json:"templates"`
	Additional   string     `json:"additional"`
	NoteType     NoteType   `json:"note_type"`
	Status       NoteStatus `json:"status"`
	Tlp          NoteTlp    `json:"tlp"`
	SourceChatID *int64     `json:"source_chat_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.Title,
		arg.Summary,
		arg.LaymansTerms,
		arg.Analogy,
		arg.CoreIdea,
		arg.Body,
		arg.Components,
		arg.WhyItMatters,
		arg.Examples,
		arg.Templates,
		arg.Additional,
		arg.NoteType,
		arg.Status,
		arg.Tlp,
		arg.SourceChatID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector FROM notes WHERE id = $1 AND user_id = $2
`

type GetNoteByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getNoteBySourceChat = `-- name: GetNoteBySourceChat :one
SELECT id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector FROM notes WHERE source_chat_id = $1 AND user_id = $2
`

type GetNoteBySourceChatParams struct {
	SourceChatID *int64 `json:"source_chat_id"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) GetNoteBySourceChat(ctx context.Context, arg GetNoteBySourceChatParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteBySourceChat, arg.SourceChatID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const listNotesByStatus = `-- name: ListNotesByStatus :many
SELECT id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector FROM notes
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotesByStatusParams struct {
	UserID int64      `json:"user_id"`
	Status NoteStatus `json:"status"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListNotesByStatus(ctx context.Context, arg ListNotesByStatusParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LaymansTerms,
			&i.Analogy,
			&i.CoreIdea,
			&i.Body,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.Status,
			&i.Tlp,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByTag = `-- name: ListNotesByTag :many
SELECT n.id, n.user_id, n.title, n.summary, n.laymans_terms, n.analogy, n.core_idea, n.body, n.components, n.why_it_matters, n.examples, n.templates, n.additional, n.note_type, n.status, n.tlp, n.source_chat_id, n.created_at, n.updated_at, n.search_vector FROM notes n
JOIN note_tags nt ON nt.note_id = n.id
JOIN tags t ON t.id = nt.tag_id
WHERE n.user_id = $1 AND t.name = $2
ORDER BY n.created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotesByTagParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotesByTag(ctx context.Context, arg ListNotesByTagParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByTag,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LaymansTerms,
			&i.Analogy,
			&i.CoreIdea,
			&i.Body,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.Status,
			&i.Tlp,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT n.id, n.user_id, n.title, n.summary, n.laymans_terms, n.analogy, n.core_idea, n.body, n.components, n.why_it_matters, n.examples, n.templates, n.additional, n.note_type, n.status, n.tlp, n.source_chat_id, n.created_at, n.updated_at, n.search_vector,
    array_agg(DISTINCT t.name) FILTER (WHERE t.name IS NOT NULL) as tag_names,
    count(DISTINCT c.id) as connection_count
FROM notes n
LEFT JOIN note_tags nt ON nt.note_id = n.id
LEFT JOIN tags t ON t.id = nt.tag_id
LEFT JOIN (
    SELECT id, source_id as note_id FROM connections
    UNION ALL
    SELECT id, target_id as note_id FROM connections
) c ON c.note_id = n.id
WHERE n.user_id = $1
GROUP BY n.id
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotesByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListNotesByUserRow struct {
	ID              int64       `json:"id"`
	UserID          int64       `json:"user_id"`
	Title           string      `json:"title"`
	Summary         string      `json:"summary"`
	LaymansTerms    string      `json:"laymans_terms"`
	Analogy         string      `json:"analogy"`
	CoreIdea        string      `json:"core_idea"`
	Body            string      `json:"body"`
	Components      string      `json:"components"`
	WhyItMatters    string      `json:"why_it_matters"`
	Examples        string      `json:"examples"`
	Templates       string      `json:"templates"`
	Additional      string      `json:"additional"`
	NoteType        NoteType    `json:"note_type"`
	Status          NoteStatus  `json:"status"`
	Tlp             NoteTlp     `json:"tlp"`
	SourceChatID    *int64      `json:"source_chat_id"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	SearchVector    interface{} `json:"search_vector"`
	TagNames        interface{} `json:"tag_names"`
	ConnectionCount int64       `json:"connection_count"`
}

func (q *Queries) ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]ListNotesByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesByUserRow{}
	for rows.Next() {
		var i ListNotesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LaymansTerms,
			&i.Analogy,
			&i.CoreIdea,
			&i.Body,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.Status,
			&i.Tlp,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.TagNames,
			&i.ConnectionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentNotes = `-- name: RecentNotes :many
SELECT id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector FROM notes
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2
`

type RecentNotesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) RecentNotes(ctx context.Context, arg RecentNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, recentNotes, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LaymansTerms,
			&i.Analogy,
			&i.CoreIdea,
			&i.Body,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.Status,
			&i.Tlp,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotes = `-- name: SearchNotes :many
SELECT id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector,
    ts_headline('english', title || ' - ' || summary || ' ' || body,
        plainto_tsquery('english', $2),
        'StartSel=<mark>, StopSel=</mark>, MaxWords=35, MinWords=15'
    ) as snippet
FROM notes
WHERE user_id = $1 AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3 OFFSET $4
`

type SearchNotesParams struct {
	UserID         int64  `json:"user_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type SearchNotesRow struct {
	ID           int64       `json:"id"`
	UserID       int64       `json:"user_id"`
	Title        string      `json:"title"`
	Summary      string      `json:"summary"`
	LaymansTerms string      `json:"laymans_terms"`
	Analogy      string      `json:"analogy"`
	CoreIdea     string      `json:"core_idea"`
	Body         string      `json:"body"`
	Components   string      `json:"components"`
	WhyItMatters string      `json:"why_it_matters"`
	Examples     string      `json:"examples"`
	Templates    string      `json:"templates"`
	Additional   string      `json:"additional"`
	NoteType     NoteType    `json:"note_type"`
	Status       NoteStatus  `json:"status"`
	Tlp          NoteTlp     `json:"tlp"`
	SourceChatID *int64      `json:"source_chat_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	SearchVector interface{} `json:"search_vector"`
	Snippet      []byte      `json:"snippet"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error) {
	rows, err := q.db.Query(ctx, searchNotes,
		arg.UserID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNotesRow{}
	for rows.Next() {
		var i SearchNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LaymansTerms,
			&i.Analogy,
			&i.CoreIdea,
			&i.Body,
			&i.Components,
			&i.WhyItMatters,
			&i.Examples,
			&i.Templates,
			&i.Additional,
			&i.NoteType,
			&i.Status,
			&i.Tlp,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET
    title = $3,
    summary = $4,
    laymans_terms = $5,
    analogy = $6,
    core_idea = $7,
    body = $8,
    components = $9,
    why_it_matters = $10,
    examples = $11,
    templates = $12,
    additional = $13,
    note_type = $14,
    status = $15,
    tlp = $16,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector
`

type UpdateNoteParams struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	Title        string     `json:"title"`
	Summary      string     `json:"summary"`
	LaymansTerms string     `json:"laymans_terms"`
	Analogy      string     `json:"analogy"`
	CoreIdea     string     `json:"core_idea"`
	Body         string     `json:"body"`
	Components   string     `json:"components"`
	WhyItMatters string     `json:"why_it_matters"`
	Examples     string     `json:"examples"`
	Templates    string     `json:"templates"`
	Additional   string     `json:"additional"`
	NoteType     NoteType   `json:"note_type"`
	Status       NoteStatus `json:"status"`
	Tlp          NoteTlp    `json:"tlp"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Summary,
		arg.LaymansTerms,
		arg.Analogy,
		arg.CoreIdea,
		arg.Body,
		arg.Components,
		arg.WhyItMatters,
		arg.Examples,
		arg.Templates,
		arg.Additional,
		arg.NoteType,
		arg.Status,
		arg.Tlp,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateNoteSourceChat = `-- name: UpdateNoteSourceChat :one
UPDATE notes SET source_chat_id = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector
`

type UpdateNoteSourceChatParams struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	SourceChatID *int64 `json:"source_chat_id"`
}

func (q *Queries) UpdateNoteSourceChat(ctx context.Context, arg UpdateNoteSourceChatParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNoteSourceChat, arg.ID, arg.UserID, arg.SourceChatID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateNoteStatus = `-- name: UpdateNoteStatus :one
UPDATE notes SET status = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, summary, laymans_terms, analogy, core_idea, body, components, why_it_matters, examples, templates, additional, note_type, status, tlp, source_chat_id, created_at, updated_at, search_vector
`

type UpdateNoteStatusParams struct {
	ID     int64      `json:"id"`
	UserID int64      `json:"user_id"`
	Status NoteStatus `json:"status"`
}

func (q *Queries) UpdateNoteStatus(ctx context.Context, arg UpdateNoteStatusParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNoteStatus, arg.ID, arg.UserID, arg.Status)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LaymansTerms,
		&i.Analogy,
		&i.CoreIdea,
		&i.Body,
		&i.Components,
		&i.WhyItMatters,
		&i.Examples,
		&i.Templates,
		&i.Additional,
		&i.NoteType,
		&i.Status,
		&i.Tlp,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
