// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note_events.sql

package sqlc

import (
	"context"
)

const createNoteEvent = `-- name: CreateNoteEvent :one
INSERT INTO note_events (note_id, user_id, from_status, to_status)
VALUES ($1, $2, $3, $4)
RETURNING id, note_id, user_id, from_status, to_status, created_at
`

type CreateNoteEventParams struct {
	NoteID     int64          `json:"note_id"`
	UserID     int64          `json:"user_id"`
	FromStatus NullNoteStatus `json:"from_status"`
	ToStatus   NoteStatus     `json:"to_status"`
}

func (q *Queries) CreateNoteEvent(ctx context.Context, arg CreateNoteEventParams) (NoteEvent, error) {
	row := q.db.QueryRow(ctx, createNoteEvent,
		arg.NoteID,
		arg.UserID,
		arg.FromStatus,
		arg.ToStatus,
	)
	var i NoteEvent
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.FromStatus,
		&i.ToStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getNoteCurrentStatus = `-- name: GetNoteCurrentStatus :one
SELECT status FROM notes WHERE id = $1 AND user_id = $2
`

type GetNoteCurrentStatusParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetNoteCurrentStatus(ctx context.Context, arg GetNoteCurrentStatusParams) (NoteStatus, error) {
	row := q.db.QueryRow(ctx, getNoteCurrentStatus, arg.ID, arg.UserID)
	var status NoteStatus
	err := row.Scan(&status)
	return status, err
}
