// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddNoteTag(ctx context.Context, arg AddNoteTagParams) error
	CountNotesByStatus(ctx context.Context, userID int64) ([]CountNotesByStatusRow, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateGlossaryTerm(ctx context.Context, arg CreateGlossaryTermParams) (GlossaryTerm, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteEvent(ctx context.Context, arg CreateNoteEventParams) (NoteEvent, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConnection(ctx context.Context, id int64) error
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteGlossaryTerm(ctx context.Context, arg DeleteGlossaryTermParams) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	GetConnectionDensity(ctx context.Context, userID int64) (GetConnectionDensityRow, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	GetConversationConversionRate(ctx context.Context, userID int64) (GetConversationConversionRateRow, error)
	GetFleetingNotesWithAge(ctx context.Context, userID int64) ([]GetFleetingNotesWithAgeRow, error)
	GetGlossaryCount(ctx context.Context, userID int64) (int32, error)
	GetGraphData(ctx context.Context, userID int64) ([]GetGraphDataRow, error)
	GetLifecycleMetrics(ctx context.Context, arg GetLifecycleMetricsParams) ([]GetLifecycleMetricsRow, error)
	GetLifecycleTrend(ctx context.Context, arg GetLifecycleTrendParams) ([]GetLifecycleTrendRow, error)
	GetMonthlyUsage(ctx context.Context, userID *int64) (GetMonthlyUsageRow, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error)
	GetNoteBySourceChat(ctx context.Context, arg GetNoteBySourceChatParams) (Note, error)
	GetNoteCurrentStatus(ctx context.Context, arg GetNoteCurrentStatusParams) (NoteStatus, error)
	GetNoteTypeDistribution(ctx context.Context, userID int64) ([]GetNoteTypeDistributionRow, error)
	GetSleepingNoteStats(ctx context.Context, userID int64) (GetSleepingNoteStatsRow, error)
	GetStaleNotes(ctx context.Context, arg GetStaleNotesParams) ([]GetStaleNotesRow, error)
	GetTagsForNote(ctx context.Context, noteID int64) ([]Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error)
	ListConnectionsForNote(ctx context.Context, sourceID int64) ([]ListConnectionsForNoteRow, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	ListGlossaryTerms(ctx context.Context, userID int64) ([]ListGlossaryTermsRow, error)
	ListMessages(ctx context.Context, conversationID int64) ([]Message, error)
	ListNotesByStatus(ctx context.Context, arg ListNotesByStatusParams) ([]Note, error)
	ListNotesByTag(ctx context.Context, arg ListNotesByTagParams) ([]Note, error)
	ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]ListNotesByUserRow, error)
	ListTagsByUser(ctx context.Context, userID int64) ([]ListTagsByUserRow, error)
	LogAIUsage(ctx context.Context, arg LogAIUsageParams) (AiUsageLog, error)
	RecentNotes(ctx context.Context, arg RecentNotesParams) ([]Note, error)
	RemoveNoteTag(ctx context.Context, arg RemoveNoteTagParams) error
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error)
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (Conversation, error)
	UpdateGlossaryTerm(ctx context.Context, arg UpdateGlossaryTermParams) (GlossaryTerm, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateNoteSourceChat(ctx context.Context, arg UpdateNoteSourceChatParams) (Note, error)
	UpdateNoteStatus(ctx context.Context, arg UpdateNoteStatusParams) (Note, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
}

var _ Querier = (*Queries)(nil)
