// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
)

const addNoteTag = `-- name: AddNoteTag :exec
INSERT INTO note_tags (note_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddNoteTagParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddNoteTag(ctx context.Context, arg AddNoteTagParams) error {
	_, err := q.db.Exec(ctx, addNoteTag, arg.NoteID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name) VALUES ($1, $2)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, name
`

type CreateTagParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.user_id, t.name FROM tags t
JOIN note_tags nt ON nt.tag_id = t.id
WHERE nt.note_id = $1
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT t.id, t.name, count(nt.note_id) as note_count
FROM tags t
LEFT JOIN note_tags nt ON nt.tag_id = t.id
WHERE t.user_id = $1
GROUP BY t.id, t.name
ORDER BY t.name
`

type ListTagsByUserRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	NoteCount int64  `json:"note_count"`
}

func (q *Queries) ListTagsByUser(ctx context.Context, userID int64) ([]ListTagsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByUserRow{}
	for rows.Next() {
		var i ListTagsByUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNoteTag = `-- name: RemoveNoteTag :exec
DELETE FROM note_tags WHERE note_id = $1 AND tag_id = $2
`

type RemoveNoteTagParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveNoteTag(ctx context.Context, arg RemoveNoteTagParams) error {
	_, err := q.db.Exec(ctx, removeNoteTag, arg.NoteID, arg.TagID)
	return err
}
