// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (oidc_subject, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at
`

type CreateUserParams struct {
	OidcSubject string `json:"oidc_subject"`
	Email       string `json:"email"`
	Name        string `json:"name"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OidcSubject,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at FROM users WHERE oidc_subject = $1
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = $2,
    name = $3,
    avatar_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at
`

type UpdateUserParams struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users SET
    preferences = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, oidc_subject, email, name, avatar_url, preferences, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	ID          int64           `json:"id"`
	Preferences json.RawMessage `json:"preferences"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.ID, arg.Preferences)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
